### ISSUE TITLE
Template: /app/client/templates/application/sidebar/header.js

### ISSUE THREAD

**Issue by christinejuruena69** [christinejuruena69/UImeteor128#10]
Do not forget to remove the click behavior. Bale dapat yung burger lang yung only way para lumabas yung sidebar, hindi yung buong header
@IJAlonzo

**Comment by IJAlonzo** [comment]
Okie dokie! :)

**Comment by IJAlonzo** [comment]
Done! Question ko lang, how would we hide the sidebar kasi maooverlap yung hamburger button e. :))

**Comment by IJAlonzo** [comment]
DOOOOONE! :+1:
